name = "onecell-gitlab-search"
main = "src/index.js"
compatibility_date = "2023-06-09"
usage_model = "bundled"
env = { }

[vars]
GITLAB_BASE_URL="https://gitlab.acme.corp"
GITLAB_TOKEN="glpat-xxxxxxxxx"


[triggers]
crons = [ ]
